### ISSUE TITLE
How to process a nested RPC framework?

### ISSUE THREAD

**Issue by wu-sheng** [opentracing/specification#18]
@adriancole @yurishkuro @bensigelman 

In distributed system, this is a common scenario: a RPC framework nested in another RPC framework.

for example:

A simple RPC call A ---->  B , uses a rpc framework (such as dubbox, popular in China), and this framework can provides rest service. And rest service provided by httpclient and tomcat lib. 

The workflow is like this: 

```
duboox_client  ---> httpclient ---> tomcat ---> dubbox-server
|<---------JVM1------------>|      |<--------JVM2----------->|
```

As `Instrumenting Frameworks` mentioned,  `OpenTracing can throw errors when an extract fails due to no span being present, so make sure to catch the errors that signify there was no injected span and not crash your server.`

So, let us suppose,  dubbox framework and tomcat support OpenTracing, and httpclient not, `tomcat` can't extract context ( extract/inject only match in dubbox ), for sure, and will create a new tracer. This will conflict with `dubbox-server` extract result.

This will happen sooner or later, What can I do in this scenario?

What's your opinion? 

@yurishkuro , Also from Chinese Open Source Community. I find it hard to decide. Some options as following:

1. After  `dubbox-server` extract, override the new tracer (from tomcat)
1. Enforce  the lib match at two sides, client and server. Seems hard.

**Comment by adriancole** [comment]
OpenTracing is an api, not an implementation. It has no specification of propagation format, so cannot solve this problem apart from containing it with common vocabulary and injection points.

For example, Uber's Jaeger uses a different propagation format than most zipkin systems. Since opentracing defines Inject/Extract, it is relatively clean to change the components to something compatible as done here: https://github.com/uber/jaeger-client-java/tree/master/jaeger-zipkin

How to address propagation incompatibility is really at the propagation tier, baggage implementation layer. For example, you could have multiple propagation formats that coexist and possibly adapt into one another on the way in or out. Regardless you end up with a coordination problem.

This is one of the reasons I opened a repo to discuss zipkin's propagation format (B3), as it is a pretty common area of concern. Ex what are the semantics used on an invalid propagation attempt?

There's usually a few choices:
* restart on malformed/unknown
* break caller on malformed
* trust (propagate and report transparently whatever you receive)

The first two take a strong opinion, that there is a format that must be present (possibly sanitized between hops). The second is a weaker opinion (attempt to parse ids propagated, but leave them alone and push them on the way). Incidentally, just today we had a [quite lengthy discussion](https://github.com/mdsol/Medidata.ZipkinTracerModule/pull/100#issuecomment-260867461) on this topic!

While not used by OpenTracing or Zipkin systems directly, there are efforts out there to discuss generic propagation, including Baggage @JonathanMace. Opinionated implementation of baggage (as opposed to library interfaces), may well surface in the next year.

**Comment by wu-sheng** [comment]
@adriancole , I have known OpenTracing just a spec, not including how to solve this scenario. But so many people interest in OT, may have solution or advices for it.

I am looking for that. ( like your choices ) Thanks. 👍

**Comment by adriancole** [comment]
@wu-sheng while low-traffic, you can also try asking here https://groups.google.com/forum/#!forum/distributed-tracing

Regardless, I think you are right... one way or another folks who end up in OpenTracing have this concern and will have something to say on this topic.

**Comment by wu-sheng** [comment]
@adriancole , As a contributor of OpenTracing.io and OpenTracing-java, also I have already finished to translate the [OpenTracing spec to Simplified Chinese](https://github.com/opentracing/opentracing.io/issues/149), can you add me a member of [opentracing org](https://github.com/opentracing)

I will hope to be a member, ^_^, this will help me to `persuade` more *Chinese Open Source Framework* to follow OpenTracing spec.

I hope to build a bridge between OpenTracing org and Chinese Open Source Team (even Enterprise App)

**Comment by adriancole** [comment]
nice! and.. done! Thanks for your help on that.

**Comment by wu-sheng** [comment]
I am a member of opentracing-org now? I can't find the badge on my github profile page. :(

**Comment by adriancole** [comment]
@wu-sheng you have to accept the invite email then maybe refresh I guess?

**Comment by wu-sheng** [comment]
I complete the confirm on github page. it seems  no email received...  Thang you.
